### ISSUE TITLE
Scripts - Karlos Messyas

### ISSUE THREAD

**Issue by SAndrade100** [AgileSysProjects/BancoDeDados2023.2#11]
Para Karlos, serão entregues:
- Três gatilhos
- Duas consultas aninhadas
- Duas consultas aninhadas correlacionadas

**Comment by KarlosMessyas** [comment]
### Consultas aninhadas

**-- Selecione a matricula dos alunos que moram no logradouro 'Rua Josival Messyas'(Consulta aninhada)**
SELECT matriculaaluno
FROM Enderecoalunos
WHERE logradouro IN(
	SELECT logradouro
 	FROM enderecoalunos
 	WHERE logradouro = 'Rua Josival Messyas'
);


**-- Selecione o nome dos professores que tem mestrado(Consulta aninhada)**
SELECT nome
FROM professores
WHERE titulacao IN(
	SELECT titulacao
 	FROM professores
 	WHERE titulacao = 'Mestrado'
);
